#!/usr/bin/env python
import numpy as np
import os
import sys
import parsnip
import time


if __name__ == '__main__':
    start_time = time.time()

    parser = parsnip.build_default_argparse('Train a ParSNIP model.')

    parser.add_argument('model')
    parser.add_argument('dataset', nargs='+')

    parser.add_argument('--no_augment', action='store_false', dest='augment')
    parser.add_argument('--overwrite', action='store_true')
    parser.add_argument('--max_epochs', type=int, default=1000)
    parser.add_argument('--split_train_test', action='store_true')

    parser.add_argument('--device', default='cuda')
    parser.add_argument('--threads', default=8, type=int)

    # Parse the arguments
    args = vars(parser.parse_args())

    # Name of the dataset
    model_name = args['model']

    # Figure out if we have already trained a model with this name.
    path = parsnip.ParsnipModel.get_model_path(model_name)
    if os.path.exists(path):
        if args['overwrite']:
            print(f"Model {model_name} already exists, overwriting!")
        else:
            print(f"Model {model_name} already exists, skipping!")
            sys.exit()

    # Load the dataset(s).
    dataset = parsnip.load_datasets(args['dataset'])

    model = parsnip.ParsnipModel(
        model_name,
        dataset.get_bands(),
        device=args['device'],
        threads=args['threads'],
        augment=args['augment'],
        settings=args,
        ignore_unknown_settings=True
    )

    model.preprocess(dataset)

    if args['split_train_test']:
        train_dataset, test_dataset = parsnip.split_train_test(dataset)
        model.fit(train_dataset, test_dataset=test_dataset,
                  max_epochs=args['max_epochs'])
    else:
        train_dataset = dataset
        model.fit(train_dataset, max_epochs=args['max_epochs'])

    # Save the score to a file for quick comparisons. If we have a small dataset,
    # repeat the dataset several times when calculating the score.
    rounds = int(np.ceil(25000 / len(train_dataset.objects)))

    train_score = model.score(train_dataset, rounds=rounds)
    if args['use_train_test']:
        test_score = model.score(test_dataset, rounds=10 * rounds)
    else:
        test_score = -1.

    end_time = time.time()

    # Time taken in minutes
    elapsed_time = (end_time - start_time) / 60.

    with open('./parsnip_results.log', 'a') as f:
        print(f'{model_name} {model.epoch} {elapsed_time:.2f} {train_score:.4f} '
              f'{test_score:.4f}', file=f)
